env:
  VARIABLE_NAME: 'Ma variable de test'
name: Mon premier workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Listing files
        run: ls -al
      - name: display variable
        run: echo ${{ env.VARIABLE_NAME }}
      - name: Use a Secret
        env:
          SUPER_SECRET: ${{ secrets.SECRET_NAME }}
        run: echo $SUPER_SECRET
      - name: Run test
        run: php bin/phpunit
